package models
package models













































}	return nil	// Your implementation herefunc Delete(id int) error {// Note: Checks will be automatically deleted due to ON DELETE CASCADE// Query: "DELETE FROM monitors WHERE id = ?"// Execute DELETE query// TODO: Implement Delete method}	return nil, nil	// Your implementation herefunc GetByID(id int) (*Monitor, error) {// Query: "SELECT id, name, url, check_interval_seconds, created_at FROM monitors WHERE id = ?"// Execute SELECT query with WHERE clause// TODO: Implement GetByID method}	return nil, nil	// Your implementation herefunc GetAll() ([]Monitor, error) {// Query: "SELECT id, name, url, check_interval_seconds, created_at FROM monitors ORDER BY created_at DESC"// Execute SELECT query to get all monitors// TODO: Implement GetAll method}	return nil, nil	// Your implementation herefunc Create(name, url string, checkInterval int) (*Monitor, error) {// 4. Get last insert ID and return complete Monitor struct// 3. Execute INSERT query: "INSERT INTO monitors (name, url, check_interval_seconds, created_at) VALUES (?, ?, ?, NOW())"// 2. Validate URL format// 1. Validate required fields (name, url)// TODO: Implement Create method}	CreatedAt            time.Time `json:"created_at"`	CheckIntervalSeconds int       `json:"check_interval_seconds"`	URL                  string    `json:"url"`	Name                 string    `json:"name"`	ID                   int       `json:"id"`type Monitor struct {import "time"